const nome = prompt("Digite seu nome completo: ")
document.body.innerHTML += `Seu nome é: ${nome}<br/>`
document.body.innerHTML += `Seu nome tem ${nome.length} letras<br/>`
document.body.innerHTML += `A segunda letra do seu nome é: ${nome[1]}<br/>`
document.body.innerHTML += `O primeiro indice da letra 'o' no seu nome: ${nome.search('o')}<br/>`
document.body.innerHTML += `O último indice da letra 'o' no seu nome: ${nome.lastIndexOf('o')}<br/>`
document.body.innerHTML += `As 3 últimas letras do seu nome: ${nome.slice(nome.length-3)}<br/>`
document.body.innerHTML += `As palavras do seu nome: ${nome.split(' ')}<br/>`
document.body.innerHTML += `Seu nome com maiúsculas: ${nome.toUpperCase()}<br/>`
document.body.innerHTML += `Seu nome com minúsculas: ${nome.toLowerCase()}<br/>`